language: node_js
os:
  - windows
node_js:
  - "8"
dist: trusty
services:
  - redis-server
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
env:
  - NODE_ENV=ci
