language: node_js
node_js:
  - "10"
dist: trusty
services:
  - redis-server
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
script:
  - nohup npm run server &
  - sleep 3
  - npm run test
env:
  - NODE_ENV= jest
